import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1780994126113 implements MigrationInterface {
    name = 'Baseline1780994126113'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "webhook_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "target_url" character varying(512) NOT NULL, "secret" character varying(128) NOT NULL, "events" jsonb NOT NULL DEFAULT '[]'::jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bf631ae77d39849d599817fb6f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9f7060b145d1cd7b8c718b1b86" ON "webhook_subscriptions" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "webhook_deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "subscription_id" uuid NOT NULL, "event" character varying(64) NOT NULL, "payload" jsonb NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'pending', "attempt_count" integer NOT NULL DEFAULT '0', "last_status" integer, "last_error" text NOT NULL DEFAULT '', "next_attempt_at" TIMESTAMP WITH TIME ZONE NOT NULL, "delivered_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_535dd409947fb6d8fc6dfc0112a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_284017efc3cbfe592288749a9c" ON "webhook_deliveries" ("status", "next_attempt_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9dce7ee955ee08740a8d48e8e" ON "webhook_deliveries" ("tenant_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "webauthn_credentials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "user_id" uuid NOT NULL, "credential_id" text NOT NULL, "public_key" text NOT NULL, "counter" bigint NOT NULL DEFAULT '0', "aaguid" character varying, "nickname" character varying NOT NULL DEFAULT 'Passkey', "transports" text array NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "last_used_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f5a100358f652926a5abae5e431" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a5f56ff95fb343a29246007bb7" ON "webauthn_credentials" ("tenant_id", "credential_id") `);
        await queryRunner.query(`CREATE TABLE "webauthn_challenges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "user_id" uuid, "challenge" text NOT NULL, "purpose" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e2946be78aa4435a952618a944d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "visits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "booking_id" uuid, "host_user_id" uuid NOT NULL, "visitor_name" character varying NOT NULL, "visitor_email" character varying NOT NULL DEFAULT '', "visitor_phone" character varying NOT NULL DEFAULT '', "visitor_company" character varying NOT NULL DEFAULT '', "purpose" character varying NOT NULL DEFAULT '', "expected_at" TIMESTAMP WITH TIME ZONE NOT NULL, "expected_until" TIMESTAMP WITH TIME ZONE, "status" character varying NOT NULL DEFAULT 'Expected', "checked_in_at" TIMESTAMP WITH TIME ZONE, "checked_out_at" TIMESTAMP WITH TIME ZONE, "nda_accepted" boolean NOT NULL DEFAULT false, "notes" character varying NOT NULL DEFAULT '', "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0b0b322289a41015c6ea4e8bf30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6a181717c874e45588ee093028" ON "visits" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_44a3b141496c9846f8b8f518e7" ON "visits" ("tenant_id", "expected_at") `);
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "code" character varying, "parent_id" uuid, "head_user_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0a8e1f8c063210d831b9b9447c" ON "departments" ("tenant_id", "name") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "username" character varying NOT NULL, "email" character varying, "password_hash" character varying NOT NULL, "must_change_password" boolean NOT NULL DEFAULT false, "dn" character varying, "role" character varying NOT NULL, "grade" character varying, "locale" character varying(16) NOT NULL DEFAULT 'en', "is_active" boolean NOT NULL DEFAULT true, "manager_id" uuid, "region_access" text array NOT NULL DEFAULT '{}', "mfa_enabled" boolean NOT NULL DEFAULT false, "mfa_secret" character varying, "mfa_enrolled_at" TIMESTAMP WITH TIME ZONE, "sso_provider" character varying, "sso_subject" character varying, "ics_feed_token" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e8786290492396a5cd9ae7f399" ON "users" ("ics_feed_token") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_52a29f8fc340e73d124af517f2" ON "users" ("tenant_id", "username") `);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2310ecc5cb8be427097154b18fc" UNIQUE ("slug"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teams_conversation_refs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "user_id" uuid NOT NULL, "aad_object_id" character varying(64) NOT NULL DEFAULT '', "service_url" character varying(512) NOT NULL, "conversation_id" character varying(512) NOT NULL, "channel_id" character varying(64) NOT NULL DEFAULT 'msteams', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0bc7041d419f3ab4c8904f84d29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4ef0e65554b394be21a366cefa" ON "teams_conversation_refs" ("aad_object_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_248ca97ef6ec55ad02450a7585" ON "teams_conversation_refs" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "calendar_sync_outbox" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "booking_id" uuid NOT NULL, "event" character varying NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'pending', "attempt_count" integer NOT NULL DEFAULT '0', "next_attempt_at" TIMESTAMP WITH TIME ZONE NOT NULL, "sent_at" TIMESTAMP WITH TIME ZONE, "last_error" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7013d8d53747e72dbcefb59435c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7cb17dc3eab197dd2e275798a" ON "calendar_sync_outbox" ("status", "next_attempt_at") `);
        await queryRunner.query(`CREATE TABLE "identity_providers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "slug" character varying NOT NULL, "name" character varying NOT NULL, "kind" character varying NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "config" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3ac9e77e3690c03f7f25579c8e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_88fe8cd3dafbd6884e0417cc7f" ON "identity_providers" ("tenant_id", "slug") `);
        await queryRunner.query(`CREATE TABLE "sso_state" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "state" character varying NOT NULL, "tenant_id" uuid NOT NULL, "provider_id" uuid NOT NULL, "kind" character varying NOT NULL, "nonce" character varying, "verifier" character varying, "redirect_after" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_aaf868267239fcdb05a3f956feb" UNIQUE ("state"), CONSTRAINT "PK_4f748d681c01bdc795158b16529" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "category_id" uuid, "name" character varying NOT NULL, "description" character varying NOT NULL DEFAULT '', "price_cents" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ba2d347a3168a296416c6c5ccb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1f103b339209a4ba9cfbee4acf" ON "services" ("tenant_id", "name") `);
        await queryRunner.query(`CREATE TABLE "booking_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "booking_id" uuid NOT NULL, "service_id" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "unit_price_cents" integer NOT NULL DEFAULT '0', "note" character varying NOT NULL DEFAULT '', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8997bf4d0728c8740c87694d59a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_813fb23d7e327b6d9cff929cce" ON "booking_services" ("booking_id") `);
        await queryRunner.query(`CREATE TABLE "sensors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "device_id" character varying NOT NULL, "resource_id" uuid, "label" character varying NOT NULL DEFAULT '', "secret_hash" character varying NOT NULL DEFAULT '', "last_seen_at" TIMESTAMP WITH TIME ZONE, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b8bd5fcfd700e39e96bcd9ba6b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3c6bb28ba65ba342572014328b" ON "sensors" ("tenant_id", "device_id") `);
        await queryRunner.query(`CREATE TABLE "sensor_readings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "sensor_id" uuid NOT NULL, "device_id" character varying NOT NULL, "resource_id" uuid, "occupancy" double precision NOT NULL DEFAULT '0', "extra" jsonb, "observed_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ae97fcc8df9e5662d9d007d102b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_af6fb7e8c939de685787d4d1f8" ON "sensor_readings" ("tenant_id", "resource_id", "observed_at") `);
        await queryRunner.query(`CREATE TABLE "scim_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "prefix" character varying NOT NULL, "token_hash" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "last_used_at" TIMESTAMP WITH TIME ZONE, "expires_at" TIMESTAMP WITH TIME ZONE, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_5e368798dfa88b0d9fb185e8901" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2f0bba718f72bfe82a482a1093" ON "scim_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE TABLE "resources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "location" character varying, "region" character varying, "asset_type" character varying NOT NULL DEFAULT 'Meeting Room', "capacity" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "is_restricted" boolean NOT NULL DEFAULT false, "requires_approval" boolean NOT NULL DEFAULT false, "parent_resource_id" uuid, "composite_mode" character varying NOT NULL DEFAULT 'standalone', "department_id" uuid, "booking_mode" character varying NOT NULL DEFAULT 'exclusive', "shared_capacity" integer NOT NULL DEFAULT '1', "operating_hours" jsonb, "equipment" jsonb, "custom_fields" jsonb, "rule_overrides" jsonb, "cost_center_code" character varying, "exchange_mailbox" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_632484ab9dff41bba94f9b7c85e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cad6c185bf17e6b3631863b5fe" ON "resources" ("tenant_id", "name") `);
        await queryRunner.query(`CREATE TABLE "resource_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "key" character varying NOT NULL, "label" character varying NOT NULL, "icon" character varying NOT NULL DEFAULT 'box', "color" character varying NOT NULL DEFAULT '#3b82f6', "default_capacity" integer NOT NULL DEFAULT '0', "default_booking_mode" character varying NOT NULL DEFAULT 'exclusive', "default_requires_approval" boolean NOT NULL DEFAULT false, "display_order" integer NOT NULL DEFAULT '0', "is_builtin" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d3bca389a6c56e445c7487b245e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_83c5c7ad52007d49b8802465ab" ON "resource_types" ("tenant_id", "key") `);
        await queryRunner.query(`CREATE TABLE "push_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "user_id" uuid NOT NULL, "endpoint" text NOT NULL, "p256dh" character varying NOT NULL, "auth" character varying NOT NULL, "user_agent" character varying NOT NULL DEFAULT '', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "last_used_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_5c9e93b19464f3fe704acf0c4bc" UNIQUE ("user_id", "endpoint"), CONSTRAINT "PK_757fc8f00c34f66832668dc2e53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0d2adb8c2d4ac8acf39adbd0e5" ON "push_subscriptions" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "role" character varying(64) NOT NULL, "permissions" text array NOT NULL DEFAULT '{}', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c1493738243af4a6af79c1a498" ON "role_permissions" ("tenant_id", "role") `);
        await queryRunner.query(`CREATE TABLE "outlook_sync_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "mailbox_upn" character varying(255) NOT NULL, "graph_id" character varying(256) NOT NULL, "ical_uid" character varying(256) NOT NULL DEFAULT '', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_96d8b5b3342e46cc433193d0967" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_59494474b9eeb83ae1daa539ce" ON "outlook_sync_records" ("booking_id") `);
        await queryRunner.query(`CREATE TABLE "notification_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "template_type" character varying(32) NOT NULL, "subject" character varying NOT NULL, "body_template" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_76f0fc48b8d057d2ae7f3a2848a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7d8ea4fa054022381597e656ed" ON "notification_templates" ("tenant_id", "template_type") `);
        await queryRunner.query(`CREATE TABLE "notification_outbox" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "booking_id" uuid, "event" character varying NOT NULL, "recipient_email" character varying NOT NULL, "vars" jsonb NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'pending', "attempt_count" integer NOT NULL DEFAULT '0', "next_attempt_at" TIMESTAMP WITH TIME ZONE NOT NULL, "sent_at" TIMESTAMP WITH TIME ZONE, "last_error" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_83d47c7dba1da2d038749fe757e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_936c616ab46210ea7fa275d052" ON "notification_outbox" ("status", "next_attempt_at") `);
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "region" character varying, "address" jsonb DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e24632d5bde06f018abb0064e0" ON "locations" ("tenant_id", "name") `);
        await queryRunner.query(`CREATE TABLE "location_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "filter_by" character varying NOT NULL DEFAULT 'Whitelist', "approvers" jsonb NOT NULL DEFAULT '[]', "locations" jsonb NOT NULL DEFAULT '[]', "member_ids" jsonb NOT NULL DEFAULT '[]', "status" character varying NOT NULL DEFAULT 'Active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_28b724510af407838c620b6b9fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_708cba88b6825545404eec1bf9" ON "location_groups" ("tenant_id", "name") `);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "department_id" uuid, "period" character varying NOT NULL, "lines" jsonb NOT NULL DEFAULT '[]', "subtotal_cents" integer NOT NULL DEFAULT '0', "tax_cents" integer NOT NULL DEFAULT '0', "total_cents" integer NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'Draft', "issued_at" TIMESTAMP WITH TIME ZONE, "paid_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_78075a77073eec4c6866682f24" ON "invoices" ("tenant_id", "department_id", "period") `);
        await queryRunner.query(`CREATE TABLE "integration_credentials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "provider" character varying(32) NOT NULL, "azure_tenant_id" character varying(128) NOT NULL DEFAULT '', "client_id" character varying(256) NOT NULL DEFAULT '', "client_secret" text NOT NULL DEFAULT '', "is_active" boolean NOT NULL DEFAULT true, "last_test_ok" boolean, "last_test_error" text NOT NULL DEFAULT '', "last_tested_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_601cd417b22e08cfbd85ba05445" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_47b331842527292d4dd73cd3f2" ON "integration_credentials" ("tenant_id", "provider") `);
        await queryRunner.query(`CREATE TABLE "integration_room_mailboxes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "resource_id" uuid NOT NULL, "mailbox_upn" character varying(255) NOT NULL, "display_name" character varying(255) NOT NULL DEFAULT '', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_28ad8665b6c999585122f522c24" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6f8f0fdc5c86c969702a1e23f2" ON "integration_room_mailboxes" ("resource_id") `);
        await queryRunner.query(`CREATE TABLE "holidays" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "holiday_date" date NOT NULL, "name" character varying NOT NULL DEFAULT '', "scope" character varying NOT NULL DEFAULT 'manual', "region" character varying NOT NULL DEFAULT '', "is_blocker" boolean NOT NULL DEFAULT true, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3646bdd4c3817d954d830881dfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_324bd7bcb2621dc97fade33189" ON "holidays" ("tenant_id", "holiday_date", "region") `);
        await queryRunner.query(`CREATE TABLE "graph_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "mailbox_upn" character varying(255) NOT NULL, "graph_subscription_id" character varying(64) NOT NULL, "client_state" character varying(128) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bae66d1146d60b4ab55d21ff9ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dfb43efcf1d3eb1183ad7b2959" ON "graph_subscriptions" ("expires_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2cd33fdd512014ab9b59d810c7" ON "graph_subscriptions" ("tenant_id", "mailbox_upn") `);
        await queryRunner.query(`CREATE TABLE "google_sync_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "calendar_id" character varying(255) NOT NULL, "event_id" character varying(256) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cf0ffc0f3f98107dbe2f8e952fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8482562d6cbadb101117e17c32" ON "google_sync_records" ("booking_id") `);
        await queryRunner.query(`CREATE TABLE "floor_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "image_url" character varying NOT NULL DEFAULT '', "shapes" jsonb NOT NULL DEFAULT '[]', "pins" jsonb NOT NULL DEFAULT '[]', "is_default" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4243d68fe3bfa6a38a2cccd5e9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f602f080fbf8619ff7006d8df4" ON "floor_plans" ("tenant_id", "name") `);
        await queryRunner.query(`CREATE TABLE "tenant_customizations" ("tenant_id" uuid NOT NULL, "data" jsonb NOT NULL DEFAULT '{}'::jsonb, "version" integer NOT NULL DEFAULT '0', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4390540c29aff508e88002f16c1" PRIMARY KEY ("tenant_id"))`);
        await queryRunner.query(`CREATE TABLE "broadcasts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "severity" character varying NOT NULL DEFAULT 'info', "color" character varying NOT NULL DEFAULT '', "image_url" character varying NOT NULL DEFAULT '', "starts_at" TIMESTAMP WITH TIME ZONE NOT NULL, "ends_at" TIMESTAMP WITH TIME ZONE NOT NULL, "filters" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b0586900034d0726bbdcb1b21b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_db5ec0eb1cd26f25d36ba2a341" ON "broadcasts" ("tenant_id", "starts_at") `);
        await queryRunner.query(`CREATE TABLE "recurrences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_by" uuid NOT NULL, "resource_id" uuid NOT NULL, "pattern" character varying(16) NOT NULL, "interval" integer NOT NULL DEFAULT '1', "count" integer, "until" TIMESTAMP WITH TIME ZONE, "byday" integer array NOT NULL DEFAULT '{}', "bymonth" integer array NOT NULL DEFAULT '{}', "rrule" text NOT NULL DEFAULT '', "status" character varying(16) NOT NULL DEFAULT 'Active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bc886e2f5042804348556c33a2c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_effcdc9275131e28d2f26abfc5" ON "recurrences" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "resource_id" uuid NOT NULL, "user_id" uuid NOT NULL, "start_time" TIMESTAMP WITH TIME ZONE NOT NULL, "end_time" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'Confirmed', "title" character varying NOT NULL DEFAULT '', "meeting_url" character varying NOT NULL DEFAULT '', "redirect_url" character varying NOT NULL DEFAULT '', "exception_notes" character varying NOT NULL DEFAULT '', "booking_mode" character varying NOT NULL DEFAULT 'exclusive', "custom_field_values" jsonb, "services" jsonb, "attendees" jsonb, "cost_center_code" character varying(64), "delegated_to" uuid, "sync_status" character varying(16) NOT NULL DEFAULT 'pending', "is_private" boolean NOT NULL DEFAULT false, "is_recurring" boolean NOT NULL DEFAULT false, "recurrence_id" uuid, "checked_in_at" TIMESTAMP WITH TIME ZONE, "checkin_token" character varying(64), "checkin_token_expires_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_08fd68619f4b3698492f5651c3" ON "bookings" ("resource_id", "start_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_50dfca880b7ef2662ba87564dc" ON "bookings" ("tenant_id", "start_time") `);
        await queryRunner.query(`CREATE TABLE "audit_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "user_id" uuid, "username" character varying NOT NULL, "action" character varying(128) NOT NULL, "severity" character varying(16) NOT NULL DEFAULT 'info', "outcome" character varying(16) NOT NULL DEFAULT 'success', "target_entity" character varying(64), "target_id" character varying(128), "method" character varying(8), "path" character varying(512), "status_code" integer, "ip" character varying(64), "user_agent" character varying(512), "previous" jsonb, "next" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_18f1b83851afc9d2d190c7c843" ON "audit_log" ("tenant_id", "outcome") `);
        await queryRunner.query(`CREATE INDEX "IDX_c02845b6e18786b05984f7ff1f" ON "audit_log" ("tenant_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_90394b4295e9068386d094c9a4" ON "audit_log" ("tenant_id", "action") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad217a94f778851d62c38b82d4" ON "audit_log" ("tenant_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "approvals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "booking_id" uuid NOT NULL, "approver_id" uuid, "decision" character varying(16) NOT NULL, "reason" character varying NOT NULL DEFAULT '', "decided_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_690417aaefa84d18b1a59e2a499" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c9136ace325201db404a09f79" ON "approvals" ("tenant_id", "booking_id") `);
        await queryRunner.query(`CREATE TABLE "approval_steps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "booking_id" uuid NOT NULL, "rule_id" uuid, "step_index" integer NOT NULL, "level_name" character varying NOT NULL, "approver_ids" text array NOT NULL DEFAULT '{}', "approver_role" character varying NOT NULL DEFAULT '', "min_grade" character varying NOT NULL DEFAULT '', "status" character varying(16) NOT NULL DEFAULT 'pending', "decided_by" uuid, "decision_at" TIMESTAMP WITH TIME ZONE, "reason" character varying NOT NULL DEFAULT '', "due_at" TIMESTAMP WITH TIME ZONE, "require_all" boolean NOT NULL DEFAULT false, "approved_by" text array NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_31089858f2c75f4648107ae5280" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4355eef3719718d8ec17f64a08" ON "approval_steps" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3debda776a31af9faaa2fea0c8" ON "approval_steps" ("tenant_id", "booking_id") `);
        await queryRunner.query(`CREATE TABLE "approval_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "scope_type" character varying(32) NOT NULL, "scope_value" character varying NOT NULL DEFAULT '', "priority" integer NOT NULL DEFAULT '100', "levels" jsonb NOT NULL DEFAULT '[]', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_048d2ffdf7169337b4cc237d772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_231552be00554aaf8c2e1eb520" ON "approval_rules" ("tenant_id", "priority") `);
        await queryRunner.query(`CREATE TABLE "user_departments" ("user_id" uuid NOT NULL, "department_id" uuid NOT NULL, CONSTRAINT "PK_2a5bce7bdcf687fe73fb534c0ee" PRIMARY KEY ("user_id", "department_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_78098f9a7c51985e96b5326bca" ON "user_departments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f10514cebc5e624f08c1b55808" ON "user_departments" ("department_id") `);
        await queryRunner.query(`ALTER TABLE "user_departments" ADD CONSTRAINT "FK_78098f9a7c51985e96b5326bca9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_departments" ADD CONSTRAINT "FK_f10514cebc5e624f08c1b558081" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_departments" DROP CONSTRAINT "FK_f10514cebc5e624f08c1b558081"`);
        await queryRunner.query(`ALTER TABLE "user_departments" DROP CONSTRAINT "FK_78098f9a7c51985e96b5326bca9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f10514cebc5e624f08c1b55808"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78098f9a7c51985e96b5326bca"`);
        await queryRunner.query(`DROP TABLE "user_departments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_231552be00554aaf8c2e1eb520"`);
        await queryRunner.query(`DROP TABLE "approval_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3debda776a31af9faaa2fea0c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4355eef3719718d8ec17f64a08"`);
        await queryRunner.query(`DROP TABLE "approval_steps"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c9136ace325201db404a09f79"`);
        await queryRunner.query(`DROP TABLE "approvals"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad217a94f778851d62c38b82d4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90394b4295e9068386d094c9a4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c02845b6e18786b05984f7ff1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18f1b83851afc9d2d190c7c843"`);
        await queryRunner.query(`DROP TABLE "audit_log"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50dfca880b7ef2662ba87564dc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08fd68619f4b3698492f5651c3"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_effcdc9275131e28d2f26abfc5"`);
        await queryRunner.query(`DROP TABLE "recurrences"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db5ec0eb1cd26f25d36ba2a341"`);
        await queryRunner.query(`DROP TABLE "broadcasts"`);
        await queryRunner.query(`DROP TABLE "tenant_customizations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f602f080fbf8619ff7006d8df4"`);
        await queryRunner.query(`DROP TABLE "floor_plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8482562d6cbadb101117e17c32"`);
        await queryRunner.query(`DROP TABLE "google_sync_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd33fdd512014ab9b59d810c7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dfb43efcf1d3eb1183ad7b2959"`);
        await queryRunner.query(`DROP TABLE "graph_subscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_324bd7bcb2621dc97fade33189"`);
        await queryRunner.query(`DROP TABLE "holidays"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f8f0fdc5c86c969702a1e23f2"`);
        await queryRunner.query(`DROP TABLE "integration_room_mailboxes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47b331842527292d4dd73cd3f2"`);
        await queryRunner.query(`DROP TABLE "integration_credentials"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78075a77073eec4c6866682f24"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_708cba88b6825545404eec1bf9"`);
        await queryRunner.query(`DROP TABLE "location_groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e24632d5bde06f018abb0064e0"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_936c616ab46210ea7fa275d052"`);
        await queryRunner.query(`DROP TABLE "notification_outbox"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d8ea4fa054022381597e656ed"`);
        await queryRunner.query(`DROP TABLE "notification_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59494474b9eeb83ae1daa539ce"`);
        await queryRunner.query(`DROP TABLE "outlook_sync_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1493738243af4a6af79c1a498"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d2adb8c2d4ac8acf39adbd0e5"`);
        await queryRunner.query(`DROP TABLE "push_subscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83c5c7ad52007d49b8802465ab"`);
        await queryRunner.query(`DROP TABLE "resource_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cad6c185bf17e6b3631863b5fe"`);
        await queryRunner.query(`DROP TABLE "resources"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f0bba718f72bfe82a482a1093"`);
        await queryRunner.query(`DROP TABLE "scim_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af6fb7e8c939de685787d4d1f8"`);
        await queryRunner.query(`DROP TABLE "sensor_readings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c6bb28ba65ba342572014328b"`);
        await queryRunner.query(`DROP TABLE "sensors"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_813fb23d7e327b6d9cff929cce"`);
        await queryRunner.query(`DROP TABLE "booking_services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f103b339209a4ba9cfbee4acf"`);
        await queryRunner.query(`DROP TABLE "services"`);
        await queryRunner.query(`DROP TABLE "sso_state"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88fe8cd3dafbd6884e0417cc7f"`);
        await queryRunner.query(`DROP TABLE "identity_providers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7cb17dc3eab197dd2e275798a"`);
        await queryRunner.query(`DROP TABLE "calendar_sync_outbox"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_248ca97ef6ec55ad02450a7585"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ef0e65554b394be21a366cefa"`);
        await queryRunner.query(`DROP TABLE "teams_conversation_refs"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52a29f8fc340e73d124af517f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8786290492396a5cd9ae7f399"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a8e1f8c063210d831b9b9447c"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44a3b141496c9846f8b8f518e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a181717c874e45588ee093028"`);
        await queryRunner.query(`DROP TABLE "visits"`);
        await queryRunner.query(`DROP TABLE "webauthn_challenges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5f56ff95fb343a29246007bb7"`);
        await queryRunner.query(`DROP TABLE "webauthn_credentials"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9dce7ee955ee08740a8d48e8e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_284017efc3cbfe592288749a9c"`);
        await queryRunner.query(`DROP TABLE "webhook_deliveries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f7060b145d1cd7b8c718b1b86"`);
        await queryRunner.query(`DROP TABLE "webhook_subscriptions"`);
    }

}
